theme: jekyll-theme-minimal
title: Oliver Gorton
description: Ph.D. Candidate from San Diego State University and University of California, Irvine, currently at Lawrence Livermore National Laboratory
show_downloads: "false"
