theme: jekyll-theme-minimal
logo: oliver.JPG
title: "About Oliver Gorton"
description: "Uses computational science to study the structure and properties of atomic nuclei for basic and applied science."
