theme: jekyll-theme-minimal
logo: oliver2.JPG
title: "About Oliver Gorton"
description: "Oliver uses scientific computing to study the structure and properties of atomic nuclei for basic and applied science."
