theme: jekyll-theme-minimal
title: "Oliver Gorton"
description: "I use scientific computing to study the structure and properties of atomic nuclei for basic and applied science."
show_downloads: false
