theme: jekyll-theme-minimal
title: "Oliver Gorton"
description: "I use scientific computing to study the structure and properties of atomic nuclei for basic and applied science. | [Education](#education) | [Publications](#publications) | [Research](#research) | [Professional](#professional) | [Training](#training) | [Code](#code) | [Awards](#awards) | [Talks](#talks) |
| - | - | - | - | - | - | - | - |"
show_downloads: false
