theme: jekyll-theme-midnight
logo: oliver2.JPG
title: "About Oliver Gorton"
description: "Uses scientific computing to study the structure and properties of atomic nuclei for basic and applied science."
